name: Run Tests
on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  build:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc-version: ['9.4.7', '9.6.3', '9.8.1', '9.10.1', '9.12.1']
    steps:
      - uses: actions/checkout@v2

      - name: Set up GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: 'latest'
          cabal-update: true

      - name: Configure the build
        run: |
          cabal configure --enable-tests
          cabal build --dry-run

      - name: Install dependencies
        run: cabal build all --only-dependencies --enable-tests

      - name: Build
        run: cabal build all --ghc-options="-Werror" --enable-tests

      - name: Run tests
        run: cabal test all --ghc-options="-Werror"
